name: Test PR with Gradle

on:
  pull_request:
    branches: [ master, develop]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < etc/sql/schema.sql
      - name: Grant Gradle permissions
        run: chmod +x gradlew
      - run: mkdir  bin
      - run: ./gradlew --version
      - name: Run Tests
        run: ./gradlew test --info